POST http://localhost:9216/essttp-backend/epaye/bta/journey/start
Accept: */*
Cache-Control: no-cache
Content-Type: Application/Json
X-Session-ID: sialalalabta

{
  "returnUrl": "http://localhost:9066/return",
  "backUrl":   "http://localhost:9066/back"
}

###

POST http://localhost:9216/essttp-backend/epaye/epaye-service/journey/start
Accept: */*
Cache-Control: no-cache
Content-Type: Application/Json
X-Session-ID: sialalalaepayeservice

{
  "returnUrl": "http://localhost:9066/return",
  "backUrl":   "http://localhost:9066/back"
}

###

POST http://localhost:9216/essttp-backend/epaye/gov-uk/journey/start
Accept: */*
Cache-Control: no-cache
Content-Type: Application/Json
X-Session-ID: sialalalagovuk

{}

###

POST http://localhost:9216/essttp-backend/epaye/detached-url/journey/start
Accept: */*
Cache-Control: no-cache
Content-Type: Application/Json
X-Session-ID: sialalaladetachedurl

{}
