### just a placeholder for now
POST http://localhost:9216/essttp-backend/vat/bta/journey/start
Accept: */*
Cache-Control: no-cache
Content-Type: Application/Json
X-Session-ID: sialalalabta

{
  "returnUrl": "http://localhost:9066/return",
  "backUrl":   "http://localhost:9066/back"
}


### just a placeholder for now
POST http://localhost:9216/essttp-backend/vat/gov-uk/journey/start
Accept: */*
Cache-Control: no-cache
Content-Type: Application/Json
X-Session-ID: sialalalagovuk

{}

### just a placeholder for now
POST http://localhost:9216/essttp-backend/vat/detached-url/journey/start
Accept: */*
Cache-Control: no-cache
Content-Type: Application/Json
X-Session-ID: sialalaladetachedurl

{}
