POST http://localhost:9216/essttp-backend/journey/6318908dbd07605ea537cdbb/update-start-dates
Accept: */*
Cache-Control: no-cache
Content-Type: Application/Json
X-Session-ID: sialalalabta

{
  "initialPaymentDate": "2022-07-03",
  "instalmentStartDate": "2022-07-28"
}
