POST http://localhost:9216/essttp-backend/journey/6318908dbd07605ea537cdbb/update-chosen-type-of-bank-account
Accept: */*
Cache-Control: no-cache
Content-Type: Application/Json
X-Session-ID: sialalalabta

"Business"