POST http://localhost:9216/essttp-backend/journey/631a0f4be737ab7d2fd83d90/update-tax-id
Accept: */*
Cache-Control: no-cache
Content-Type: Application/Json
X-Session-ID: sialalalabta

{
  "EmpRef": {
    "value": "016GZ91926"
  }
}
