POST http://localhost:9216/essttp-backend/journey/6283a6f14f01006f33b859b8/update-extreme-dates
Accept: */*
Cache-Control: no-cache
Content-Type: Application/Json
X-Session-ID: sialalaladetachedurl

{
  "initialPaymentDate": "2022-01-01",
  "earliestPlanStartDate": "2022-02-01",
  "latestPlanStartDate": "2022-03-01"
}