GET http://localhost:9216/essttp-backend/journey/:journeyId
Accept: */*
Cache-Control: no-cache
Content-Type: Application/Json
X-Session-ID: sialalala

###


GET http://localhost:9216/essttp-backend/journey/find-latest-by-session-id
Accept: */*
Cache-Control: no-cache
Content-Type: Application/Json
X-Session-ID: sialalala

###