POST http://localhost:9000/essttp-backend/epaye/bta/journey/start
Accept: */*
Cache-Control: no-cache
Content-Type: Application/Json
X-Session-ID: sialalala

{
  "returnUrl": "http://localhost:9066/return",
  "backUrl":   "http://localhost:9066/back"
}

###

POST http://localhost:9000/essttp-backend/epaye/gov-uk/journey/start
Accept: */*
Cache-Control: no-cache
Content-Type: Application/Json
X-Session-ID: sialalala

{
}

###

POST http://localhost:9000/essttp-backend/epaye/detached-url/journey/start
Accept: */*
Cache-Control: no-cache
Content-Type: Application/Json
X-Session-ID: sialalala

{
}